todo/models.py
"""
models.py

Contains all the models related to tasks
"""
import datetime
from application import db


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    description = db.Column(db.String(80), nullable=False)
    start_date = db.Column(db.DateTime, nullable=False,
                           default=datetime.date.today())
    end_date = db.Column(db.DateTime)
    status = db.Column(db.Boolean)

    owner = db.relationship('User',
                            backref=db.backref('task', lazy='dynamic'))

    def __init__(self, user, description, start_date, end_date, status=False):
        self.owner = user
        self.description = description
        self.start_date = start_date
        self.end_date = end_date
        self.status = status


    def __repr__(self):
        return f'<Task {self.description}>'

user/models.py
"""
models.py

Contains User model for user app
"""
from application import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(80))
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(128))

    def __init__(self, full_name, email, password):
        self.full_name = full_name
        self.email = email
        self.password = password

    def __repr__(self):
        return f'<User {self.full_name}>'

todo/forms.py
"""
forms.py

Contains add new task form
"""
from flask import session
from flask_wtf import FlaskForm
from wtforms import validators
from wtforms import StringField
from wtforms.fields.html5 import DateField
from wtforms import BooleanField


class AddTaskForm(FlaskForm):
   description = StringField('Description', [validators.InputRequired(),
                                             validators.Length(min=5, max=80)])
   start_date = DateField('Start date')
   end_date = DateField('End date')

user/forms.py
"""
forms.py

Contains register and login form for user app
"""
from flask_wtf import FlaskForm
from wtforms import validators
from wtforms import StringField
from wtforms import PasswordField
from wtforms import ValidationError
from wtforms.fields.html5 import EmailField
from werkzeug.security import check_password_hash

from user.models import User


class LoginForm(FlaskForm):
    email = StringField('Email',
                        [validators.InputRequired(),
                         validators.Email()])
    password = PasswordField('New Password',
                             [validators.Required(),
                              validators.Length(min=4, max=80)])

    def validate(self):
        rv = FlaskForm.validate(self)
        if not rv:
            return False

        user = User.query.filter_by(email=self.email.data).first()

        if user:
            if not check_password_hash(user.password, self.password.data):
                self.password.errors.append('Incorrect email or password')
                return False
            return True
        else:
            self.password.errors.append('Incorrect email or password')
            return False

class RegisterForm(FlaskForm):
    full_name = StringField('Full Name', [validators.InputRequired()])
    email = EmailField('Email Address',
                       [validators.InputRequired(),
                        validators.Email()])
    password = PasswordField('New Password',
                             [validators.Required(),
                              validators.Length(min=4, max=80)])
    confirm = PasswordField('Repeat Password',
                            [validators.EqualTo('password', message='Passwords must match')])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Email already in use, please use a different one.')

todo/views.py
"""
views.py

Contains all the views related to todo app
"""
from flask import Blueprint
from flask import render_template
from flask import session
from flask import redirect
from flask import url_for
from flask import flash
from flask import request

from application import db
from .forms import AddTaskForm
from .models import Task
from user.models import User
from user.decorators import login_required


todo_app = Blueprint('todo_app', __name__)


@todo_app.route('/')
def index():
    """
    Index page
    """
    return render_template('todo/index.html')

@todo_app.route('/home')
@login_required
def home():
    """
    Home page
    """
    page = int(request.values.get('page', '1'))
    user = User.query.get(session['id'])
    tasks = Task.query.filter_by(owner=user).paginate(page, 5, False)

    return render_template('todo/home.html', tasks=tasks)

@todo_app.route('/add-task', methods=('GET', 'POST'))
@login_required
def add_task():
    """
    Task page
    """
    form = AddTaskForm()
    if form.validate_on_submit():
        user = User.query.get(session['id'])
        task = Task(
            user,
            form.description.data,
            form.start_date.data,
            form.end_date.data,
        )

        db.session.add(task)
        db.session.commit()
        flash('Task was added successfully')
        return redirect(url_for('.home'))
    return render_template('todo/add_task.html', form=form)

@todo_app.route('/delete/<int:task_id>')
@login_required
def delete(task_id):
    """
    Delete task
    """
    task = Task.query.get(task_id)
    if task:
        Task.query.filter_by(id=task_id).delete()
        db.session.commit()
        flash(f'Task <{task.description}> was deleted>')
        return redirect(url_for('.home'))

@todo_app.route('/check/<int:task_id>')
@login_required
def check(task_id):
    """
    Mark task as done
    """
    task = Task.query.get(task_id)
    if task:
        task.status = True
        db.session.commit()
        return redirect(url_for('.home'))

@todo_app.route('/uncheck/<int:task_id>')
@login_required
def uncheck(task_id):
    """
    Mark task as undone
    """
    task = Task.query.get(task_id)
    if task:
        task.status = False
        db.session.commit()
        return redirect(url_for('.home'))

user/views.py
"""
views.py

Contains all the views related to user app
"""
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import url_for
from flask import request
from flask import session
from flask import flash
from werkzeug.security import generate_password_hash

from application import db
from user.models import User
from user.forms import RegisterForm
from user.forms import LoginForm


user_app = Blueprint('user_app', __name__)


@user_app.route('/register', methods=('GET', 'POST'))
def register():
    """
    Register page
    """
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user = User(
            form.full_name.data,
            form.email.data,
            hashed_password,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))
    return render_template('user/register.html', form=form)


@user_app.route('/login', methods=('GET', 'POST'))
def login():
    """
    Login page
    """
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next', None)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        session['id'] = user.id
        session['full_name'] = user.full_name
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            return redirect(url_for('todo_app.index'))

    return render_template('user/login.html', form=form, error=error)



@user_app.route('/logout')
def logout():
    """
    Logout page
    """
    session.pop('id')
    session.pop('full_name')
    flash('User loggerd out')
    return redirect(url_for('.login'))

templates/_flashmessages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="messages">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fase show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!doctype html>
<html lang="en">


  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
  </head>
  

  <body>

      {% block nav %}{% endblock %}

      <!-- Main Container -->
      <div class="container">
          
          {% block content %}{% endblock %}

      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script 
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
    </script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script> 
    <script 
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> 
    </script>
  </body>
</html>

templates/nav.html
<div class="container pb-3">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if session.id %}
    <a class="navbar-brand" href="{{ url_for('todo_app.index') }}">
        Welcome {{ session.full_name }}!
    </a>
    {% else %}
    <a class="navbar-brand" href="{{ url_for('todo_app.index') }}">
       Todo Application 
    </a>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if session.id %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('todo_app.add_task')}}">
            New Task
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('todo_app.home')}}">
            Tasks
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user_app.logout')}}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user_app.register')}}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user_app.login')}}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

templates/todo/add_task.html
{% extends "base.html" %}

{% block title %}New Task{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

  <div class="offset-md-2 col-md-8">

    {% include '_flashmessages.html'  %}

    <h4>New task</h4>

    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('.add_task')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.description, class='form-control') }}
      {{ render_field(form.start_date, class='form-control') }}
      {{ render_field(form.end_date, class='form-control') }}

      <button type="submit" class="btn btn-primary">Add</button>

    </form>

  </div>

</div>
{% endblock %}

templates/todo/home.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8 pt-5">

        {% include '_flashmessages.html' %}

        {% include 'todo/tasks.html'  %}
    </div>
    <div class="offset-md-2 col-md-8 pt-5">
      {% if tasks.has_prev %}
        <a href="{{ url_for('todo_app.home', page=tasks.prev_num) }}">&lt;&lt; Previous Page</a>
      {% endif %}
      {% if tasks.has_next %}
        <a href="{{ url_for('todo_app.home', page=tasks.next_num) }}">Next Page &gt;&gt;</a>
      {% endif %}
  </div>

</div>

{% endblock content %}

templates/todo/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8 pt-5">
        <h4>Wlecome!</h4>
        <p>
        Simple Todo application written using FLask along with the 
        following extensions:
        </p>
        <ul>
            <li>Flask-SQLAlchemy</li>
            <li>Flask-Migrate</li>
            <li>Flask-WTF</li>
        </ul>
    </div>

</div>

{% endblock content %}

templates/todo/tasks.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Description</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks.items %}
    <tr>
        <th scope="row">{{ task.id }}</th>
        <td>{{ task.description }}</td>
        <td>{{ task.start_date.strftime('%Y-%m-%d') }}</td>
        <td>{{ task.end_date.strftime('%Y-%m-%d') }}</td>
        <td>{{ task.status }}</td>
        <td>
            <a href={{ url_for('.check', task_id=task.id) }}>
                <img src={{ url_for('static', filename='icons/check.png') }}>
            </a>
            <a href={{ url_for('.uncheck', task_id=task.id) }}>
                <img src={{ url_for('static', filename='icons/uncheck.png') }}>
            </a>
            <a href={{ url_for('.delete', task_id=task.id) }}>
                <img src={{ url_for('static', filename='icons/delete.png') }}>
            </a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/user/login.html
{% extends "base.html" %}

{% block title %}User Login{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
    <div class="offset-md-2 col-md-8">
        {% include '_flashmessages.html' %}

        <h4>User Login</h4>

        {% from '_formhelpers.html' import render_field %}
        <form method="POST" action="{{ url_for('.login') }}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.email, class='form-control') }}
            {{ render_field(form.password, class='form-control') }}

            <button type="submit" class="btn btn-primary">Login</button>

        </form>
    </div>
</div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}User Registration{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

  <div class="offset-md-2 col-md-8">

    <h4>User Registration</h4>

    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('.register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.full_name, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}
      {{ render_field(form.password, class='form-control') }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-primary">Register</button>

    </form>

  </div>

</div>
{% endblock %}